### ISSUE TITLE
whate is mean of attribute 'T'

### ISSUE THREAD

**Issue by huibinGe** [VahidooX/DeepCCA#12]
Traceback (most recent call last):
  File "DeepCCA.py", line 153, in <module>
    learning_rate, reg_par, outdim_size, use_all_singular_values)
  File "/Users/gehuibin/Desktop/DeepCCA-master/models.py", line 22, in create_model
    model.compile(loss=cca_loss(outdim_size, use_all_singular_values), optimizer=model_optimizer)
  File "/Users/gehuibin/anaconda3/lib/python3.6/site-packages/keras/models.py", line 781, in compile
    **kwargs)
  File "/Users/gehuibin/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 840, in compile
    sample_weight, mask)
  File "/Users/gehuibin/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 446, in weighted
    score_array = fn(y_true, y_pred)
  File "/Users/gehuibin/Desktop/DeepCCA-master/objectives.py", line 22, in inner_cca_objective
    H1 = y_pred[:, 0:o1].T
AttributeError: 'Tensor' object has no attribute 'T'

**Comment by gongshuai0606** [comment]
> Traceback (most recent call last): File "DeepCCA.py", line 153, in learning_rate, reg_par, outdim_size, use_all_singular_values) File "/Users/gehuibin/Desktop/DeepCCA-master/models.py", line 22, in create_model model.compile(loss=cca_loss(outdim_size, use_all_singular_values), optimizer=model_optimizer) File "/Users/gehuibin/anaconda3/lib/python3.6/site-packages/keras/models.py", line 781, in compile **kwargs) File "/Users/gehuibin/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 840, in compile sample_weight, mask) File "/Users/gehuibin/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 446, in weighted score_array = fn(y_true, y_pred) File "/Users/gehuibin/Desktop/DeepCCA-master/objectives.py", line 22, in inner_cca_objective H1 = y_pred[:, 0:o1].T AttributeError: 'Tensor' object has no attribute 'T'

I meet the same error, too. Did you solve it?
