### ISSUE TITLE
kwarg error

### ISSUE THREAD

**Issue by raniasaidi** [VahidooX/DeepCCA#18]
Hello :)
I hope you are doing well. I'm getting this error:
```
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "./DeepCCA.py", line 153, in <module>
    learning_rate, reg_par, outdim_size, use_all_singular_values)
  File "/home/enx/Downloads/DeepCCA-master2/models.py", line 19, in create_model
    model.add(concatenate([view1_model, view2_model], mode='concat'))
  File "/home/enx/Downloads/DeepCCA-master2/deepcca2_p27/local/lib/python2.7/site-packages/keras/layers/merge.py", line 384, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/home/enx/Downloads/DeepCCA-master2/deepcca2_p27/local/lib/python2.7/site-packages/keras/layers/merge.py", line 133, in __init__
    super(Concatenate, self).__init__(**kwargs)
  File "/home/enx/Downloads/DeepCCA-master2/deepcca2_p27/local/lib/python2.7/site-packages/keras/layers/merge.py", line 15, in __init__
    super(_Merge, self).__init__(**kwargs)
  File "/home/enx/Downloads/DeepCCA-master2/deepcca2_p27/local/lib/python2.7/site-packages/keras/engine/topology.py", line 275, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'mode')
```
How can i fix this ? thank you

**Comment by Pooventhiran** [comment]
@raniasaidi, concatenate functional API does not need take this "mode" argument. It was used when Merge layer was used to denote what kind of merge mode you would want.
Please remove "mode" argument and it will work.
